#配置端口和拦截
server:
  port: 8081
  servlet:
    path: "*.do"
#配置日志信息
logging:
  level:
    com.xiaoshenlong: debug
    org.mybatis: debug
#配置服务名称
spring:
  application:
    name: user-client
#配置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
#熔断器超时时长全局配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 10
        sleepWindowInMilliseconds: 10000
        errorThresholdPercentage: 50